@baseUrl = http://localhost:3333
@authToken = {{authenticate_admin.response.body.$.access_token}}

# @name create_admin
POST {{baseUrl}}/accounts/admin
Content-Type: application/json

{
  "name": "John Doe",
  "cpf": "123.123.123-01",
  "password": "123456"
}

###

# @name authenticate_admin
POST {{baseUrl}}/sessions/admin
Content-Type: application/json

{
  "cpf": "123.123.123-01",
  "password": "123456"
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "customerId": "fb4b652f-3120-4fed-8dd2-1b8df9d263d3",
  "description": "Package 01"
}
