@baseUrl = http://localhost:3333
@authTokenAdmin = {{authenticate_admin.response.body.$.access_token}}
@authTokenDeliveryman = {{authenticate_deliveryman.response.body.$.access_token}}
@authTokenRecipient = {{authenticate_recipient.response.body.$.access_token}}

# @name authenticate_admin
POST {{baseUrl}}/sessions/admin
Content-Type: application/json

{
  "cpf": "123.123.123-01",
  "password": "123456"
}

###

# @name authenticate_recipient
POST {{baseUrl}}/sessions/recipient
Content-Type: application/json

{
  "cpf": "123.123.123-02",
  "password": "123456"
}

###

# @name authenticate_deliveryman
POST {{baseUrl}}/sessions/deliveryman
Content-Type: application/json

{
  "cpf": "123.123.123-03",
  "password": "123456"
}

### ACCOUNT

# @name create_admin
POST {{baseUrl}}/accounts/admin
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
  "name": "John Doe",
  "cpf": "123.123.123-03",
  "password": "123456"
}

###

# @name create_recipient
POST {{baseUrl}}/accounts/recipient
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
  "name": "John Doe 2",
  "cpf": "123.123.123-02",
  "password": "123456",
  "street": "Rua Belo Horizonte",
  "number": 1000,
  "neighborhood": "Centro",
  "city": "Cláudio",
  "cep": "35530000"
}

###

# @name create_deliveryman
POST {{baseUrl}}/accounts/deliveryman
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
  "name": "John Doe 3",
  "cpf": "123.123.123-03",
  "password": "123456"
}

### ORDER

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
  "customerId": "{{create_recipient.response.body.$.recipient.id}}",
  "description": "Package 01"
}

###

# @name post_order
PATCH {{baseUrl}}/orders/{{create_order.response.body.$.order.id}}/post
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

###

# @name withdraw_order
PATCH {{baseUrl}}/orders/{{create_order.response.body.$.order.id}}/withdraw
Content-Type: application/json
Authorization: Bearer {{authTokenDeliveryman}}

###

# @name upload_image
POST {{baseUrl}}/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authTokenDeliveryman}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample-upload.png"
Content-Type: image/png

< ./test/e2e/sample-upload.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name deliver_order
PATCH {{baseUrl}}/orders/{{create_order.response.body.$.order.id}}/deliver
Content-Type: application/json
Authorization: Bearer {{authTokenDeliveryman}}

{
  "imageId": "{{upload_image.response.body.$.imageId}}"
}

### NOTIFICATION

# @name fetch_notifications
GET {{baseUrl}}/notifications
Content-Type: application/json
Authorization: Bearer {{authTokenRecipient}}
